name: beakerx
channels:
  - conda-forge
dependencies:
  - ipywidgets
  - beakerx
  - traitlets
  - jupyterlab==0.33.11
  - pip:
    - jupyterlab_launcher
    - ipywidgets
    - jupyter_contrib_nbextensions
